name: adhan_prayer_salah_times
description: "Adhan Prayer Times App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_islamic_icons: ^1.0.2
  share_plus: ^10.0.2
  # 🔔 Notifications
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_compass: ^0.8.1
  vibration: ^3.1.5
  url_launcher: ^6.3.0 #for google qibla finder bottom
  # 📍 Location
  geolocator: ^9.0.2
  geocoding: ^2.2.0
  # 🌐 API
  http: ^1.1.0



  # 🌍 Date / formatting hijiri calander
  table_calendar: ^3.1.2
  intl: ^0.20.2
  hijri: ^3.0.0

  # 💾 Local storage (OFFLINE SUPPORT)
  shared_preferences: ^2.3.5

  # 🌐 Internet detection (OFFLINE BANNER)
  connectivity_plus: ^6.0.5

  # 🍎 UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true

  assets:
    - assets/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true